server:
  port: 9090

spring:
  application:
    name: neo4j-text2sql-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: api
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: frontend
          uri: http://127.0.0.1:3000
          predicates:
            - Path=/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO

